package com.wx.model;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment_num
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.like_num
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tag
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.is_deleted
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.creator
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment_num
     *
     * @return the value of article.comment_num
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment_num
     *
     * @param commentNum the value for article.comment_num
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.like_num
     *
     * @return the value of article.like_num
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.like_num
     *
     * @param likeNum the value for article.like_num
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tag
     *
     * @return the value of article.tag
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tag
     *
     * @param tag the value for article.tag
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.is_deleted
     *
     * @return the value of article.is_deleted
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.is_deleted
     *
     * @param isDeleted the value for article.is_deleted
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.creator
     *
     * @return the value of article.creator
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.creator
     *
     * @param creator the value for article.creator
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbg.generated Thu Apr 08 20:29:52 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}